### ISSUE TITLE
Fehler unite type Wh not supported

### ISSUE THREAD

**Issue by sigi2345** [DutchmanNL/ioBroker.sourceanalytix#4]
`Hallo, bekomme folgenden Fehler:
( Wahrscheinlich werden deshalb keine Objekte angelegt?) 

sourceanalytix.0 | 2019-01-14 13:09:20.896 | error | Sorry unite type Wh not supported yet
-- | -- | -- | --
sourceanalytix.0 | 2019-01-14 13:09:20.896 | info | Activate SourceAnalytix for : hm-rpc.1.NEQ1662322.2.ENERGY_COUNTER
sourceanalytix.0 | 2019-01-14 13:09:20.847 | info | SourceanAlytix startet, initializing all states
sourceanalytix.0 | 2019-01-14 13:09:20.846 | info | starting. Version 0.1.0 in C:/ioBroker/node_modules/iobroker.sourceanalytix, node: v8.15.0
sourceanalytix.0 | 2019-01-14 13:09:20.741 | debug | statesDB connected
sourceanalytix.0 | 2019-01-14 13:09:20.729 | debug | objectDB connected
host.Medion | 2019-01-14 13:09:20.412 | info | instance system.adapter.sourceanalytix.0 started with pid 6400

`

![screenshot 1562](https://user-images.githubusercontent.com/41079106/51112722-e9e97000-17ff-11e9-8cfc-c893d86865bc.png)

LOG:

[iobroker.2019-01-14 - Kopie2.log](https://github.com/DutchmanNL/ioBroker.sourceanalytix/files/2755123/iobroker.2019-01-14.-.Kopie2.log)

Sigi

**Comment by DutchmanNL** [comment]
will be added today in version 0.1.5

**Comment by sigi2345** [comment]
THX

**Comment by DutchmanNL** [comment]
we only close when its done and working ;)

please try version 0.1.1 (just updated) wh calculations should work now.
Please note, values in states are always translated to kw/h 

commit = https://github.com/DutchmanNL/ioBroker.sourceanalytix/commit/b105f420fc9de4a6980518dc348fefec4dd992c4

**Comment by sigi2345** [comment]
> we only close when its done and working ;)
> 
> Sorry..........

**Comment by DutchmanNL** [comment]
> we only close when its done and working ;)
> 
> Sorry..........

no problem :)

release 0.1.2 please check if wh is handled correctly now

https://github.com/DutchmanNL/ioBroker.sourceanalytix/commit/a99740fee593b756879aa59f811a9dacbf9f0feb

**Comment by DutchmanNL** [comment]
Solved https://github.com/DutchmanNL/ioBroker.sourceanalytix/commit/6d35e1123f0945c63c33de014db195a70fc86b75
